# Generated by Django 5.2.11 on 2026-02-06 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notion_token", models.CharField(blank=True, max_length=255)),
                ("canvas_token", models.CharField(blank=True, max_length=255)),
                ("school_domain", models.CharField(blank=True, max_length=255)),
                ("db_properties", models.JSONField(default=list)),
                ("notion_page_id", models.CharField(blank=True, max_length=255)),
                ("notion_database_id", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
