# Generated by Django 5.2.11 on 2026-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="notion_database_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="notion_page_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
